### ISSUE TITLE
Level 34 becomes unbeatable

### ISSUE THREAD

**Issue by Elektron72** [SlithyMatt/x16-chasevault#13]
I was on level 34 and had no keys at the time, when eventually, the skull in the corner started shooting fireballs in a pattern that made it impossible to proceed.
https://youtu.be/ray5JHGSrmA

**Comment by SlithyMatt** [comment]
Level 34 is designed to be unbeatable without a key. So, if you plan on going through that level, make sure you have a key. Otherwise, take a different route. Only levels 1, 47, and 48 are required to beat the game.
