### ISSUE TITLE
Artifact not picked up on corners

### ISSUE THREAD

**Issue by Cyber-EX** [SlithyMatt/x16-chasevault#14]
If I turn around corner very quckly, as early as possible, the artifact on that corner won't be picked up. So I literaly have to make sure that I bump into the wall before making a turn. I find it odd. Is it intended behavior?

**Comment by SlithyMatt** [comment]
That is intended behavior. Like some versions of Pac-Man, you can cut corners to evade enemies, but that comes at the cost of missing pellets if you haven't gone through there before.

**Comment by Cyber-EX** [comment]
No, I haven't played Pac-Man versions with such behaviour. Or I could have missed it.
After a closer look I noticed this behaviour on 1:24 in this video: https://www.youtube.com/watch?v=f6d036XFiTk
Thank you for explanation!
