### ISSUE TITLE
Thoughts behind loadvram

### ISSUE THREAD

**Issue by JimmyDansbo** [SlithyMatt/x16-chasevault#3]
Is it possible you could expand a bit on your thoughts behind the loadvram function?
As far as I am aware, you can not load data directly into VRAM with the LOAD function, but then were do you actually store the data?
The addresses are shifted right 4 times before you call loadvram which means that VRAM_TILEMAP becomes $0400. If you load the tilemap at that address, do you not overwrite your code at $080D and up ?

**Comment by SlithyMatt** [comment]
Sorry for not replying earlier! Actually, you can load directly into VRAM with the X16 LOAD Kernal function. It is heavily modified from the original CBM version to use the "SA" argument for VERA bank when the value is 2 or higher. So, SA 2 is VRAM bank 0, SA 3 is VRAM bank 1, and SA 17 is register bank 15($F).
