### ISSUE TITLE
Check YM2151 busy on real hardware

### ISSUE THREAD

**Issue by rossato** [SlithyMatt/x16-chasevault#7]
On a real YM2151 you need to wait a minimum interval between writes.  You can check if the chip is ready by reading bit 7 of either address, it will be high when busy, low when ready (the emulator always returns low, so no worries there).  Chase Vault has less/glitchy sound on FPGA hardware (it gets better over time played, but never perfect).

**Comment by SlithyMatt** [comment]
Thanks! I will look into this.

**Comment by SlithyMatt** [comment]
Pull request merged into master.
