### ISSUE TITLE
Joystick support broken

### ISSUE THREAD

**Issue by rossato** [SlithyMatt/x16-chasevault#9]
On both the emulator and FPGA hardware, only the start button works on real joysticks.  This is because the joystick_tick routine assumes JOYSTICK_GET will set X to 0x01, which it only does for keyboard joystick emulation.

**Comment by SlithyMatt** [comment]
What emulator release broke this? I'm not sure if I tested my USB SNES-style controller with the latest build (R37), but it definitely worked for earlier builds.

**Comment by rossato** [comment]
I've only tested on r37.  Not sure when/if it changed, but here's the current documentation for [joystick_get](https://github.com/commanderx16/x16-docs/blob/master/Commander%20X16%20Programmer's%20Reference%20Guide.md#function-name-joystick_get).  This should be reproduceable in the emulator, I tried with both "-joy1 SNES" and "-joy1 NES".

**Comment by SlithyMatt** [comment]
Fix committed to master. Same bug also existed with joystick 2, but only showed up in joystick test program, not game. Added that fix in addition to pull request.
